wger/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import (
    index,
    sitemap
)
from django.urls import path

# Third Party
from rest_framework import routers

# wger
from wger.core.api import views as core_api_views
from wger.exercises.api import views as exercises_api_views
from wger.exercises.sitemap import ExercisesSitemap
from wger.manager.api import views as manager_api_views
from wger.nutrition.api import views as nutrition_api_views
from wger.nutrition.sitemap import NutritionSitemap
from wger.utils.generic_views import TextTemplateView
from wger.weight.api import views as weight_api_views


#admin.autodiscover()


#
# REST API
#
router = routers.DefaultRouter()

#
# Application
#

# Manager app
router.register(r'day', manager_api_views.DayViewSet, basename='day')
router.register(r'set', manager_api_views.SetViewSet, basename='Set')
router.register(r'setting', manager_api_views.SettingViewSet, basename='Setting')
router.register(r'workout', manager_api_views.WorkoutViewSet, basename='workout')
router.register(r'workoutsession', manager_api_views.WorkoutSessionViewSet, basename='workoutsession')
router.register(r'workoutlog', manager_api_views.WorkoutLogViewSet, basename='workoutlog')
router.register(r'schedulestep', manager_api_views.ScheduleStepViewSet, basename='schedulestep')
router.register(r'schedule', manager_api_views.ScheduleViewSet, basename='schedule')

# Core app
router.register(r'daysofweek', core_api_views.DaysOfWeekViewSet, basename='daysofweek')
router.register(r'language', core_api_views.LanguageViewSet, basename='language')
router.register(r'license', core_api_views.LicenseViewSet, basename='license')
router.register(r'userprofile', core_api_views.UserProfileViewSet, basename='userprofile')
router.register(r'setting-repetitionunit', core_api_views.RepetitionUnitViewSet, basename='setting-repetition-unit')
router.register(r'setting-weightunit', core_api_views.WeightUnitViewSet, basename='setting-weight-unit')

# Exercises app
router.register(r'exerciseinfo', exercises_api_views.ExerciseInfoViewset, basename='exerciseinfo')
router.register(r'exercise', exercises_api_views.ExerciseViewSet, basename='exercise')
router.register(r'equipment', exercises_api_views.EquipmentViewSet, basename='api')
router.register(r'exercisecategory', exercises_api_views.ExerciseCategoryViewSet, basename='exercisecategory')
router.register(r'exerciseimage', exercises_api_views.ExerciseImageViewSet, basename='exerciseimage')
router.register(r'exercisecomment', exercises_api_views.ExerciseCommentViewSet, basename='exercisecomment')
router.register(r'muscle', exercises_api_views.MuscleViewSet, basename='muscle')

# Nutrition app
router.register(r'ingredient', nutrition_api_views.IngredientViewSet, basename='api-ingredient')
router.register(r'ingredientinfo', nutrition_api_views.IngredientInfoViewSet, basename='api-ingredientinfo')
router.register(r'weightunit', nutrition_api_views.WeightUnitViewSet, basename='weightunit')
router.register(r'ingredientweightunit', nutrition_api_views.IngredientWeightUnitViewSet, basename='ingredientweightunit')
router.register(r'nutritionplan', nutrition_api_views.NutritionPlanViewSet, basename='nutritionplan')
router.register(r'nutritionplaninfo', nutrition_api_views.NutritionPlanInfoViewSet, basename='nutritionplaninfo')
router.register(r'nutritiondiary', nutrition_api_views.LogItemViewSet, basename='nutritiondiary')
router.register(r'meal', nutrition_api_views.MealViewSet, basename='meal')
router.register(r'mealitem', nutrition_api_views.MealItemViewSet, basename='mealitem')

# Weight app
router.register(r'weightentry', weight_api_views.WeightEntryViewSet, basename='weightentry')

#
# Sitemaps
#
sitemaps = {'exercises': ExercisesSitemap,
            'nutrition': NutritionSitemap}

#
# The actual URLs
#
urlpatterns = i18n_patterns(
    #url(r'^admin/', admin.site.urls),
    path('', include(('wger.core.urls', 'core'), namespace='core')),
    path('workout/', include(('wger.manager.urls', 'manager'), namespace='manager')),
    path('exercise/', include(('wger.exercises.urls', 'exercise'), namespace='exercise')),
    path('weight/', include(('wger.weight.urls', 'weight'), namespace='weight')),
    path('nutrition/', include(('wger.nutrition.urls', 'nutrition'), namespace='nutrition')),
    path('software/', include(('wger.software.urls', 'software'), namespace='software')),
    path('config/', include(('wger.config.urls', 'config'), namespace='config')),
    path('gym/', include(('wger.gym.urls', 'gym'), namespace='gym')),
    path('email', include(('wger.mailer.urls', 'email'), namespace='email')),
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='sitemap'),
    path('sitemap-<section>.xml',
         sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
)

#
# URLs without language prefix
#
urlpatterns += [
    path('robots.txt',
         TextTemplateView.as_view(template_name="robots.txt"),
         name='robots'),

    # API
    path('api/v2/exercise/search/',
         exercises_api_views.search,
         name='exercise-search'),
    path('api/v2/exerciseinfo/search/',
         exercises_api_views.search,
         name='exercise-info'),
    path('api/v2/ingredient/search/',
         nutrition_api_views.search,
         name='ingredient-search'),
    path('api/v2/', include(router.urls)),

    # The api user login
    path('api/v2/login/', core_api_views.UserAPILoginView.as_view({
         'post': 'post'}), name='api_user'),
    path('api/v2/register/', core_api_views.UserAPIRegistrationViewSet.as_view({
         'post': 'post'}), name='api_register'),

    # Others
    path('api/v2/version/', core_api_views.ApplicationVersionView.as_view({
        'get': 'get'}), name='app_version'),

]

#
# URL for user uploaded files, served like this during development only
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wger/weight/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Django
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

# wger
from wger.weight import views
from wger.weight.forms import WeightCsvImportForm


urlpatterns = [
    path('add/',
         login_required(views.WeightAddView.as_view()),
         name='add'),

    path('<int:pk>/edit/',
         login_required(views.WeightUpdateView.as_view()),
         name='edit'),

    path('<int:pk>/delete/',
         views.WeightDeleteView.as_view(),
         name='delete'),

    path('export-csv/',
         views.export_csv,
         name='export-csv'),
    path('import-csv/',
         login_required(views.WeightCsvImportFormPreview(WeightCsvImportForm)),
         name='import-csv'),

    url(r'^overview/(?P<username>[\w.@+-]+)$',
        views.overview,
        name='overview'),
    # url(r'^overview/$',
    #     views.overview,
    #     name='overview'),
    url(r'^api/get_weight_data/(?P<username>[\w.@+-]+)$',  # JS
        views.get_weight_data,
        name='weight-data'),
    path('api/get_weight_data/',  # JS
         views.get_weight_data,
         name='weight-data'),
]

wger/weight/api/views.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Third Party
from rest_framework import viewsets

# wger
from wger.weight.api.serializers import WeightEntrySerializer
from wger.weight.models import WeightEntry


class WeightEntryViewSet(viewsets.ModelViewSet):
    """
    API endpoint for nutrition plan objects
    """
    serializer_class = WeightEntrySerializer
    is_private = True
    ordering_fields = '__all__'
    filterset_fields = ('date',
                        'weight')

    def get_queryset(self):
        """
        Only allow access to appropriate objects
        """
        return WeightEntry.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        """
        Set the owner
        """
        serializer.save(user=self.request.user)

wger/weight/views.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

# Standard Library
import csv
import datetime
import logging

# Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import (
    Max,
    Min
)
from django.http import (
    HttpResponse,
    HttpResponseRedirect
)
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import (
    ugettext as _,
    ugettext_lazy
)
from django.views.generic import (
    CreateView,
    DeleteView,
    UpdateView
)

# Third Party
from formtools.preview import FormPreview
from rest_framework.decorators import api_view
from rest_framework.response import Response

# wger
from wger.utils.generic_views import (
    WgerDeleteMixin,
    WgerFormMixin
)
from wger.utils.helpers import check_access
from wger.weight import helpers
from wger.weight.forms import WeightForm
from wger.weight.models import WeightEntry


logger = logging.getLogger(__name__)


class WeightAddView(WgerFormMixin, CreateView):
    """
    Generic view to add a new weight entry
    """
    model = WeightEntry
    form_class = WeightForm
    title = ugettext_lazy('Add weight entry')

    def get_initial(self):
        """
        Set the initial data for the form.

        Read the comment on weight/models.py WeightEntry about why we need
        to pass the user here.
        """
        return {'user': self.request.user,
                'date': datetime.date.today()}

    def form_valid(self, form):
        """
        Set the owner of the entry here
        """
        form.instance.user = self.request.user
        return super(WeightAddView, self).form_valid(form)

    def get_success_url(self):
        """
        Return to overview with username
        """
        return reverse('weight:overview', kwargs={'username': self.object.user.username})


class WeightUpdateView(WgerFormMixin, LoginRequiredMixin, UpdateView):
    """
    Generic view to edit an existing weight entry
    """
    model = WeightEntry
    form_class = WeightForm

    def get_context_data(self, **kwargs):
        context = super(WeightUpdateView, self).get_context_data(**kwargs)
        context['title'] = _('Edit weight entry for the %s') % self.object.date

        return context

    def get_success_url(self):
        """
        Return to overview with username
        """
        return reverse('weight:overview', kwargs={'username': self.object.user.username})


class WeightDeleteView(WgerDeleteMixin, LoginRequiredMixin, DeleteView):
    """
    Generic view to delete a weight entry
    """

    model = WeightEntry
    fields = ('weight',)

    messages = ugettext_lazy('Successfully deleted.')

    def get_context_data(self, **kwargs):
        context = super(WeightDeleteView, self).get_context_data(**kwargs)
        context['title'] = _('Delete weight entry for the %s') % self.object.date
        return context

    def get_success_url(self):
        """
        Return to overview with username
        """
        return reverse('weight:overview', kwargs={'username': self.object.user.username})


@login_required
def export_csv(request):
    """
    Exports the saved weight data as a CSV file
    """

    # Prepare the response headers
    response = HttpResponse(content_type='text/csv')

    # Convert all weight data to CSV
    writer = csv.writer(response)

    weights = WeightEntry.objects.filter(user=request.user)
    writer.writerow([_('Weight'), _('Date')])

    for entry in weights:
        writer.writerow([entry.weight, entry.date])

    # Send the data to the browser
    response['Content-Disposition'] = 'attachment; filename=Weightdata.csv'
    response['Content-Length'] = len(response.content)
    return response


def overview(request, username=None):
    """
    Shows a plot with the weight data

    More info about the D3 library can be found here:
        * https://github.com/mbostock/d3
        * http://d3js.org/
    """
    is_owner, user = check_access(request.user, username)

    template_data = {}

    min_date = WeightEntry.objects.filter(user=user).\
        aggregate(Min('date'))['date__min']
    max_date = WeightEntry.objects.filter(user=user).\
        aggregate(Max('date'))['date__max']
    if min_date:
        template_data['min_date'] = 'new Date(%(year)s, %(month)s, %(day)s)' % \
                                    {'year': min_date.year,
                                     'month': min_date.month,
                                     'day': min_date.day}
    if max_date:
        template_data['max_date'] = 'new Date(%(year)s, %(month)s, %(day)s)' % \
                                    {'year': max_date.year,
                                     'month': max_date.month,
                                     'day': max_date.day}

    last_weight_entries = helpers.get_last_entries(user)

    template_data['is_owner'] = is_owner
    template_data['owner_user'] = user
    template_data['show_shariff'] = is_owner
    template_data['last_five_weight_entries_details'] = last_weight_entries
    return render(request, 'overview.html', template_data)


@api_view(['GET'])
def get_weight_data(request, username=None):
    """
    Process the data to pass it to the JS libraries to generate an SVG image
    """

    is_owner, user = check_access(request.user, username)

    date_min = request.GET.get('date_min', False)
    date_max = request.GET.get('date_max', True)

    if date_min and date_max:
        weights = WeightEntry.objects.filter(user=user,
                                             date__range=(date_min, date_max))
    else:
        weights = WeightEntry.objects.filter(user=user)

    chart_data = []

    for i in weights:
        chart_data.append({'date': i.date,
                           'weight': i.weight})

    # Return the results to the client
    return Response(chart_data)


class WeightCsvImportFormPreview(FormPreview):
    preview_template = 'import_csv_preview.html'
    form_template = 'import_csv_form.html'

    def get_context(self, request, form):
        """
        Context for template rendering.
        """

        return {'form': form,
                'stage_field': self.unused_name('stage'),
                'state': self.state}

    def process_preview(self, request, form, context):
        context['weight_list'], context['error_list'] = helpers.parse_weight_csv(request,
                                                                                 form.cleaned_data)
        return context

    def done(self, request, cleaned_data):
        weight_list, error_list = helpers.parse_weight_csv(request, cleaned_data)
        WeightEntry.objects.bulk_create(weight_list)
        return HttpResponseRedirect(reverse('weight:overview',
                                            kwargs={'username': request.user.username}))

wger/weight/templates/import_csv_form.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}

{% block title %}{% trans "Import weight logs" %}{% endblock %}

{% block content %}
<form action="{{request.get_full_path}}" method="post">
    {% crispy form %}
    <input type="submit" name="submit" value="{% trans 'Submit' %}" class="btn btn-primary btn-success btn-block" id="submit-id-submit">
</form>
{% endblock %}


{% block sidebar %}
<p>{% blocktrans %}Use this import field to import your weight logs into Workout
Manager.{% endblocktrans %}</p>

<p>{% blocktrans %}You can copy and paste from your spreadsheet into the text input,
the system will try to guess the format to import. The only things to consider is
that the first column is the <strong>date</strong>, the second the <strong>weight</strong>.
All further columns are ignored. There is a 1000 row limit.
{% endblocktrans %}</p>

<p>{% blocktrans %}If there are errors, you can correct or discard them in a
second step.{% endblocktrans %}</p>

{% endblock %}

wger/weight/templates/import_csv_preview.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}

{% block title %}{% trans "Preview imported CSV entries" %}{% endblock %}



{% block content %}
<h4>{% trans "Successfully converted values" %}</h4>
<div class="alert alert-success">{% trans "The following values could be converted." %}</div>
<table class="table">
<tr>
    <th>{% trans "Date" %}</th>
    <th>{% trans "Weight" %}</th>
</tr>
{% for entry in weight_list %}
    <tr>
        <td>{{ entry.date|date:"SHORT_DATE_FORMAT" }}</td>
        <td>{{ entry.weight }}</td>
    </tr>
{% endfor %}
</table>



<h4>{% trans "Errors" %}</h4>

{% if error_list %}
    <div class="alert alert-danger">{% trans "The following values could not be converted." %}</div>

    <p>{% blocktrans %}These values could not be converted to a weight log entry.
    The reasons for this could be anything from an unrecognised date or number
    format, a problem with the encoding or something else. Please check that
    there are no obvious errors in the list (and correct them if there are!)
    and try to import the list again.{% endblocktrans %}</p>

    <p>{% blocktrans %}Remember that the expected structure is <strong>date</strong>
    on the first columns and <strong>weight</strong> on the second.{% endblocktrans %}</p>

    <table class="table">
    <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Weight" %}</th>
    </tr>
    {% for entry in error_list %}
        <tr>
            <td>{{ entry.0 }}</td>
            <td>{{ entry.1 }}</td>
        </tr>
    {% endfor %}
</table>

{% else %}
    <p>{% blocktrans %}There were no errors, all entries could be converted!{% endblocktrans %}</p>
{% endif %}


<h2>{% trans "Import all successfully converted entries" %}</h2>
<p>{% blocktrans %}Continue here if you want to import into your weight log all
entries that were successfully converted. All entries that produced an error
will simply be ignored. It's up to you to decide whether they are useful
(unrecognised entries) or not (e.g. headers, comments, etc.).{% endblocktrans %}</p>

<form action="{{request.get_full_path}}" method="post">

    <input type="hidden" name="{{ stage_field }}" value="2" />
    <input type="hidden" name="{{ hash_field }}" value="{{ hash_value }}" />
    {% crispy form %}
    <input type="submit" name="submit" value="{% trans 'Import' %}" class="btn btn-primary btn-success btn-block" id="submit-id-submit">
</form>



<h2>{% trans "Or try it again" %}</h2>

<p>{% blocktrans %}You can correct the list here and re-submit it as often as
you want.{% endblocktrans %}</p>

<form action="{{request.get_full_path}}"
      method="post"
      class="form">

    <input type="hidden" name="{{ stage_field }}" value="1" />
    {% crispy form %}
    <input type="submit" name="submit" value="{% trans 'Re-Submit' %}" class="btn btn-primary btn-success btn-block" id="submit-id-submit">
</form>

{% endblock %}

wger/weight/templates/overview.html
{% extends "base.html" %}
{% load i18n static wger_extras %}

{#       #}
{# Title #}
{#       #}
{% block title %}{% trans "Weight overview" %}{% endblock %}

{#        #}
{# Header #}
{#        #}
{% block header %}
<script src="{% static 'js/weight.js' %}"></script>
{% endblock %}



{#         #}
{# Content #}
{#         #}
{% block content %}
<div id="current-username" data-current-username="{{ owner_user.username }}"></div>


{% if not min_date %}
<p>
    {% trans "There is no chart here because there are no weight entries." %}
    {% trans "Use link to add one." %}
</p>
{% endif %}

<div id="weight_diagram"></div>
<br>
<input id="height" placeholder="height in cm" type="number">
<input id="enable_bmi" type="button" value="BMI">

<div class="btn-group modify-time-period-controls float-right" role="group" aria-label="..." style="padding-bottom: 1em;">
    <button type="button" class="btn btn-light" data-time_period="90">{% trans "Last 3 months" %}</button>
    <button type="button" class="btn btn-light" data-time_period="365">{% trans "Last 12 months" %}</button>
    <button type="button" class="btn btn-light active" data-time_period="all">{% trans "No filter" %}</button>
</div>


{% if is_owner %}
{% if last_five_weight_entries_details %}
<table class="table">
    <tr>
        <th>{% trans 'Date' %}</th>
        <th>{% trans 'Weight' %}</th>
        <th>{% trans 'Change' context "Noun, not verb" %}</th>
        <th>{% trans 'Days' %}</th>
    </tr>
    {% for entry_detail in last_five_weight_entries_details %}
        <tr>
            <td>{{ entry_detail.0.date }}</td>
            <td>{{ entry_detail.0.weight }}</td>
            <!-- weight diff and day diff below -->
            <td>
                {% if entry_detail.1 > 0 %}
                    +
                {% endif %}
                {% if entry_detail.1 %}
                    {{ entry_detail.1 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
            <td>
                {% if entry_detail.2 %}
                    {{ entry_detail.2 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
            <td>
                <div class="btn-group" role="group" >
                    <div class="btn-group" role="group">
                        <button id="btnGroupWorkout" type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupWorkout">
                            <a href="{% url 'weight:edit' entry_detail.0.id %}" class="dropdown-item wger-modal-dialog">
                               <span class="{% fa_class 'edit' %}"></span>
                               {% trans "Edit weight" %}
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'weight:delete' entry_detail.0.id %}" class="dropdown-item wger-modal-dialog">
                                <span class="{% fa_class 'trash' %}"></span>
                                {% trans "Delete" %}
                            </a>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}
</table>
{% endif %}
{% endif %}

{% endblock %}


{#          #}
{# Side bar #}
{#          #}
{% block sidebar %}
{% endblock %}



{#         #}
{# Options #}
{#         #}
{% block options %}
{% if is_owner %}
<div class="btn-group">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="{% fa_class 'cog' %}"></span>
            {% trans "Options" %}
        </button>

        <div class="dropdown-menu">
            <a href="{% url 'weight:export-csv' %}" target="_blank" class="dropdown-item">
                <span class="{% fa_class 'download' %}"></span>
                {% trans "Export as CSV" %}
            </a>
            <a href="{% url 'weight:import-csv' %}" class="dropdown-item">
                <span class="{% fa_class 'upload' %}"></span>
                {% trans "Import from spreadsheet" %}
            </a>
        </div>
    </div>
</div>
<a href="{% url 'weight:add' %}" class="btn btn-success btn-sm wger-modal-dialog">
    {% trans "Add" %}
</a>
{% endif %}
{% endblock %}