wger/exercises/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Django
from django.conf.urls import (
    include,
    url
)
from django.contrib.auth.decorators import login_required
from django.urls import path

# wger
from wger.exercises.views import (
    categories,
    comments,
    equipment,
    exercises,
    images,
    muscles
)


# sub patterns for muscles
patterns_muscle = [
    path('overview/',
         muscles.MuscleListView.as_view(),
         name='overview'),
    path('admin-overview/',
         muscles.MuscleAdminListView.as_view(),
         name='admin-list'),
    path('add/',
         muscles.MuscleAddView.as_view(),
         name='add'),
    path('<int:pk>/edit/',
         muscles.MuscleUpdateView.as_view(),
         name='edit'),
    path('<int:pk>/delete/',
         muscles.MuscleDeleteView.as_view(),
         name='delete'),
]

# sub patterns for exercise images
patterns_images = [
    path('<int:exercise_pk>/image/add',
         images.ExerciseImageAddView.as_view(),
         name='add'),
    path('<int:pk>/edit',
         images.ExerciseImageEditView.as_view(),
         name='edit'),
    path('<int:exercise_pk>/image/<int:pk>/delete',
         images.ExerciseImageDeleteView.as_view(),
         name='delete'),
    path('<int:pk>/accept/',
         images.accept,
         name='accept'),
    path('<int:pk>/decline/',
         images.decline,
         name='decline'),
]

# sub patterns for exercise comments
patterns_comment = [
    path('<int:exercise_pk>/comment/add/',
         comments.ExerciseCommentAddView.as_view(),
         name='add'),
    path('<int:pk>/edit/',
         comments.ExerciseCommentEditView.as_view(),
         name='edit'),
    path('<int:id>/delete/',
         comments.delete,
         name='delete'),
]

# sub patterns for categories
patterns_category = [
    path('list',
         categories.ExerciseCategoryListView.as_view(),
         name='list'),
    path('<int:pk>/edit/',
         categories.ExerciseCategoryUpdateView.as_view(),
         name='edit'),
    path('add/',
         categories.ExerciseCategoryAddView.as_view(),
         name='add'),
    path('<int:pk>/delete/',
         categories.ExerciseCategoryDeleteView.as_view(),
         name='delete'),
]

# sub patterns for equipment
patterns_equipment = [
    path('list',
         equipment.EquipmentListView.as_view(),
         name='list'),
    path('add',
         equipment.EquipmentAddView.as_view(),
         name='add'),
    path('<int:pk>/edit',
         equipment.EquipmentEditView.as_view(),
         name='edit'),
    path('<int:pk>/delete',
         equipment.EquipmentDeleteView.as_view(),
         name='delete'),
    path('overview',
         equipment.EquipmentOverviewView.as_view(),
         name='overview'),
]


# sub patterns for exercises
patterns_exercise = [
    path('overview/',
         exercises.ExerciseListView.as_view(),
         name='overview'),
    path('<int:id>/view/',
         exercises.view,
         name='view'),
    url(r'^(?P<id>\d+)/view/(?P<slug>[-\w]*)/?$',
        exercises.view,
        name='view'),
    path('add/',
         login_required(exercises.ExerciseAddView.as_view()),
         name='add'),
    path('<int:pk>/edit/',
         exercises.ExerciseUpdateView.as_view(),
         name='edit'),
    path('<int:pk>/correct',
         exercises.ExerciseCorrectView.as_view(),
         name='correct'),
    path('<int:pk>/delete/',
         exercises.ExerciseDeleteView.as_view(),
         name='delete'),
    path('pending/',
         exercises.PendingExerciseListView.as_view(),
         name='pending'),
    path('<int:pk>/accept/',
         exercises.accept,
         name='accept'),
    path('<int:pk>/decline/',
         exercises.decline,
         name='decline'),
]


urlpatterns = [
    path('muscle/', include((patterns_muscle, 'muscle'), namespace="muscle")),
    path('image/', include((patterns_images, 'image'), namespace="image")),
    path('comment/', include((patterns_comment, 'comment'), namespace="comment")),
    path('category/', include((patterns_category, 'category'), namespace="category")),
    path('equipment/', include((patterns_equipment, 'equipment'), namespace="equipment")),
    path('', include((patterns_exercise, 'exercise'), namespace="exercise")),
]

wger/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import (
    index,
    sitemap
)
from django.urls import path

# Third Party
from rest_framework import routers

# wger
from wger.core.api import views as core_api_views
from wger.exercises.api import views as exercises_api_views
from wger.exercises.sitemap import ExercisesSitemap
from wger.manager.api import views as manager_api_views
from wger.nutrition.api import views as nutrition_api_views
from wger.nutrition.sitemap import NutritionSitemap
from wger.utils.generic_views import TextTemplateView
from wger.weight.api import views as weight_api_views


#admin.autodiscover()


#
# REST API
#
router = routers.DefaultRouter()

#
# Application
#

# Manager app
router.register(r'day', manager_api_views.DayViewSet, basename='day')
router.register(r'set', manager_api_views.SetViewSet, basename='Set')
router.register(r'setting', manager_api_views.SettingViewSet, basename='Setting')
router.register(r'workout', manager_api_views.WorkoutViewSet, basename='workout')
router.register(r'workoutsession', manager_api_views.WorkoutSessionViewSet, basename='workoutsession')
router.register(r'workoutlog', manager_api_views.WorkoutLogViewSet, basename='workoutlog')
router.register(r'schedulestep', manager_api_views.ScheduleStepViewSet, basename='schedulestep')
router.register(r'schedule', manager_api_views.ScheduleViewSet, basename='schedule')

# Core app
router.register(r'daysofweek', core_api_views.DaysOfWeekViewSet, basename='daysofweek')
router.register(r'language', core_api_views.LanguageViewSet, basename='language')
router.register(r'license', core_api_views.LicenseViewSet, basename='license')
router.register(r'userprofile', core_api_views.UserProfileViewSet, basename='userprofile')
router.register(r'setting-repetitionunit', core_api_views.RepetitionUnitViewSet, basename='setting-repetition-unit')
router.register(r'setting-weightunit', core_api_views.WeightUnitViewSet, basename='setting-weight-unit')

# Exercises app
router.register(r'exerciseinfo', exercises_api_views.ExerciseInfoViewset, basename='exerciseinfo')
router.register(r'exercise', exercises_api_views.ExerciseViewSet, basename='exercise')
router.register(r'equipment', exercises_api_views.EquipmentViewSet, basename='api')
router.register(r'exercisecategory', exercises_api_views.ExerciseCategoryViewSet, basename='exercisecategory')
router.register(r'exerciseimage', exercises_api_views.ExerciseImageViewSet, basename='exerciseimage')
router.register(r'exercisecomment', exercises_api_views.ExerciseCommentViewSet, basename='exercisecomment')
router.register(r'muscle', exercises_api_views.MuscleViewSet, basename='muscle')

# Nutrition app
router.register(r'ingredient', nutrition_api_views.IngredientViewSet, basename='api-ingredient')
router.register(r'ingredientinfo', nutrition_api_views.IngredientInfoViewSet, basename='api-ingredientinfo')
router.register(r'weightunit', nutrition_api_views.WeightUnitViewSet, basename='weightunit')
router.register(r'ingredientweightunit', nutrition_api_views.IngredientWeightUnitViewSet, basename='ingredientweightunit')
router.register(r'nutritionplan', nutrition_api_views.NutritionPlanViewSet, basename='nutritionplan')
router.register(r'nutritionplaninfo', nutrition_api_views.NutritionPlanInfoViewSet, basename='nutritionplaninfo')
router.register(r'nutritiondiary', nutrition_api_views.LogItemViewSet, basename='nutritiondiary')
router.register(r'meal', nutrition_api_views.MealViewSet, basename='meal')
router.register(r'mealitem', nutrition_api_views.MealItemViewSet, basename='mealitem')

# Weight app
router.register(r'weightentry', weight_api_views.WeightEntryViewSet, basename='weightentry')

#
# Sitemaps
#
sitemaps = {'exercises': ExercisesSitemap,
            'nutrition': NutritionSitemap}

#
# The actual URLs
#
urlpatterns = i18n_patterns(
    #url(r'^admin/', admin.site.urls),
    path('', include(('wger.core.urls', 'core'), namespace='core')),
    path('workout/', include(('wger.manager.urls', 'manager'), namespace='manager')),
    path('exercise/', include(('wger.exercises.urls', 'exercise'), namespace='exercise')),
    path('weight/', include(('wger.weight.urls', 'weight'), namespace='weight')),
    path('nutrition/', include(('wger.nutrition.urls', 'nutrition'), namespace='nutrition')),
    path('software/', include(('wger.software.urls', 'software'), namespace='software')),
    path('config/', include(('wger.config.urls', 'config'), namespace='config')),
    path('gym/', include(('wger.gym.urls', 'gym'), namespace='gym')),
    path('email', include(('wger.mailer.urls', 'email'), namespace='email')),
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='sitemap'),
    path('sitemap-<section>.xml',
         sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
)

#
# URLs without language prefix
#
urlpatterns += [
    path('robots.txt',
         TextTemplateView.as_view(template_name="robots.txt"),
         name='robots'),

    # API
    path('api/v2/exercise/search/',
         exercises_api_views.search,
         name='exercise-search'),
    path('api/v2/exerciseinfo/search/',
         exercises_api_views.search,
         name='exercise-info'),
    path('api/v2/ingredient/search/',
         nutrition_api_views.search,
         name='ingredient-search'),
    path('api/v2/', include(router.urls)),

    # The api user login
    path('api/v2/login/', core_api_views.UserAPILoginView.as_view({
         'post': 'post'}), name='api_user'),
    path('api/v2/register/', core_api_views.UserAPIRegistrationViewSet.as_view({
         'post': 'post'}), name='api_register'),

    # Others
    path('api/v2/version/', core_api_views.ApplicationVersionView.as_view({
        'get': 'get'}), name='app_version'),

]

#
# URL for user uploaded files, served like this during development only
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wger/utils/models.py
# -*- coding: utf-8 -*-

# This file is part of Workout Manager.
#
# Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

# Django
from django.db import models
from django.utils.translation import ugettext_lazy as _

# wger
from wger.core.models import License


"""
Abstract model classes
"""


class AbstractLicenseModel(models.Model):
    """
    Abstract class that adds license information to a model
    """

    class Meta:
        abstract = True

    license = models.ForeignKey(License,
                                verbose_name=_('License'),
                                default=2,
                                on_delete=models.CASCADE)
    """The item's license"""

    license_author = models.CharField(verbose_name=_('Author'),
                                      max_length=50,
                                      blank=True,
                                      null=True,
                                      help_text=_('If you are not the author, enter the name or '
                                                  'source here. This is needed for some licenses '
                                                  'e.g. the CC-BY-SA.'))
    """The author if it is not the uploader"""


class AbstractSubmissionModel(models.Model):
    """
    Abstract class used for model for user submitted data.

    These models have to be approved first by an administrator before they are
    shows in the website. There is also a manager that can be used:
    utils.managers.SubmissionManager
    """

    class Meta:
        abstract = True

    STATUS_PENDING = '1'
    STATUS_ACCEPTED = '2'
    STATUS_DECLINED = '3'

    STATUS = (
        (STATUS_PENDING, _('Pending')),
        (STATUS_ACCEPTED, _('Accepted')),
        (STATUS_DECLINED, _('Declined')),
    )

    status = models.CharField(max_length=2,
                              choices=STATUS,
                              default=STATUS_PENDING,
                              editable=False)
    """Status of the submission, e.g. accepted or declined"""

wger/exercises/views/comments.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

# Standard Library
import logging

# Django
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import ugettext_lazy
from django.views.generic import (
    CreateView,
    UpdateView
)

# wger
from wger.exercises.forms import CommentForm
from wger.exercises.models import (
    Exercise,
    ExerciseComment
)
from wger.utils.generic_views import WgerFormMixin


logger = logging.getLogger(__name__)


# ************************
#    Exercise comments
# ************************


class ExerciseCommentEditView(WgerFormMixin,
                              LoginRequiredMixin,
                              PermissionRequiredMixin,
                              UpdateView):
    """
    Generic view to update an existing exercise comment
    """

    model = ExerciseComment
    form_class = CommentForm
    title = ugettext_lazy('Edit')
    permission_required = 'exercises.change_exercisecomment'

    def get_success_url(self):
        return reverse('exercise:exercise:view', kwargs={'id': self.object.exercise.id})


class ExerciseCommentAddView(WgerFormMixin,
                             LoginRequiredMixin,
                             PermissionRequiredMixin,
                             CreateView):
    """
    Generic view to add a new exercise comment
    """

    model = ExerciseComment
    form_class = CommentForm
    title = ugettext_lazy('Add exercise comment')
    permission_required = 'exercises.add_exercisecomment'

    def form_valid(self, form):
        form.instance.exercise = Exercise.objects.get(pk=self.kwargs['exercise_pk'])
        return super(ExerciseCommentAddView, self).form_valid(form)

    def get_success_url(self):
        return reverse('exercise:exercise:view', kwargs={'id': self.object.exercise.id})


@permission_required('exercises.delete_exercisecomment')
def delete(request, id):
    # Load the comment
    comment = get_object_or_404(ExerciseComment, pk=id)
    exercise_id = comment.exercise.id
    comment.delete()

    return HttpResponseRedirect(reverse('exercise:exercise:view', kwargs={'id': exercise_id}))

wger/exercises/templates/exercise/form.html
{% load i18n %}

{% if not perms.exercises %}
<h4>{% trans "Submitting an exercise" %}</h4>
<p><strong>{% blocktrans %}Thank you for submitting an exercise. This is much
appreciated!{% endblocktrans %}</strong></p>

<p>{% blocktrans %}After you submit the form, the administrators will be notified.
Once it is reviewed, it will be added to the database. Till this happens,
it will not be visible in the overview or the search. In case you added your email
when you registered, you will get notified when the process is completed successfully.{% endblocktrans %}</p>
{% endif %}

wger/exercises/templates/exercise/form_correct.html
{% load i18n %}

{% if not perms.exercises %}
<h4>{% trans "Correcting an exercise" %}</h4>
<p><strong>{% blocktrans %}Thank you for correcting and improving this exercise.
This is much appreciated!{% endblocktrans %}</strong></p>

<p>{% blocktrans %}After you submit the form, the administrators will be notified.
Once the changes are reviewed the exercise will be updated.{% endblocktrans %}</p>
{% endif %}

wger/exercises/templates/exercise/pending.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load wger_extras %}

{% block title %}{% trans "Exercises pending review" %}{% endblock %}


{% block content %}

<table class="table">
<thead>
<tr>
    <th>{% trans "Submission date" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "User" %}</th>
</tr>
</thead>
<tbody>
{% for exercise in exercise_list %}
<tr>
    <td>
        {{exercise.creation_date}}
    </td>
    <td><a href="{{ exercise.get_absolute_url }}">{{exercise.name}}</a></td>
    <td>{{exercise.license_author}}</td>
</tr>
{% empty %}
<tr>
    <td colspan="2">{% trans "Nothing found" %}</td>
</tr>
{% endfor %}
</tbody>

</table>
<div style="padding-top:3em;"></div>
{% endblock %}

wger/exercises/templates/exercise/view.html
{% extends "base.html" %}
{% load i18n static wger_extras thumbnail cache django_bootstrap_breadcrumbs %}


{#           #}
{# Opengraph #}
{#           #}
{% block opengraph %}
    {{ block.super }}
    <meta property="og:title" content="{{ exercise.name }}">
    <meta property="og:description" content="{{ exercise.description_clean }}">
{% endblock %}
{% block opengraphimages %}
    {% for image in exercise.images.accepted %}
        <meta property="og:image" content="{{ image.image.url }}">
    {% empty %}
        <meta property="og:image" content="{{ image_absolute_path }}">
    {% endfor %}
{% endblock %}


{#       #}
{# Title #}
{#       #}
{% block title %}{{ exercise.name }}{% endblock %}


{#        #}
{# Header #}
{#        #}
{% block header %}
<script>
$(document).ready(function() {
    wgerDrawWeightLogChart({{json|safe}}, "{{svg_uuid}}");
});
</script>
{% endblock %}


{#         #}
{# Content #}
{#         #}
{% block content %}

{% if exercise.status == exercise.STATUS_PENDING %}
<div class="card text-white bg-dark mb-4">
    <div class="card-header">
        {% trans "Exercise is pending review" %}
    </div>
    <div class="card-body">
        <p>{% blocktrans %}This user submitted exercise is pending a decision to be
        included in the database.{% endblocktrans %}
        {% trans "Till then, it will not be shown in the overview or the search."  %}
        {% if perms.exercises.add_exercise %}{% trans "Please select one of the options below." %}{% endif %}
        </p>

        {% if perms.exercises.add_exercise %}
            <a href="{% url 'exercise:exercise:accept' exercise.id %}" class="btn btn-secondary">
                <span class="{% fa_class 'check' %}"></span>
                {% trans "Accept" %}
            </a>
            <a href="{% url 'exercise:exercise:decline' exercise.id %}" class="btn btn-secondary">
                <span class="{% fa_class 'times' %}"></span>
                {% trans "Decline" %}
            </a>
            <a href="{% url 'exercise:exercise:delete' exercise.id %}" class="wger-modal-dialog btn btn-secondary">
                <span class="{% fa_class 'trash' %}"></span>
                {% trans "Delete" %}
            </a>
        {% endif %} {# end check permissions #}
    </div>
</div>
{% endif %} {# end exercise is pending review #}


<h5 class="mt-4">{% trans "Category" %}:</h5>
{% trans exercise.category.name %}

{% if exercise.equipment.all %}
    <h5 class="mt-4">{% trans "Equipment" %}:</h5>
    {% for equipment in exercise.equipment.all %}
        {% trans equipment.name %}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
{% endif %}


<h5 class="mt-4">{% trans "Description" %}:</h5>
{{ exercise.description|safe }}



{# Images #}
{% with images=exercise.images.accepted %}
{% if images or perms.exercises.change_exerciseimage  %}
    <h5 class="mt-4">{% trans "Images" %}:</h5>
    <div class="row row-cols-2 row-cols-md-3">
    {% with other_images=images %}
    {% for image in other_images %}

        <div class="col mb-4">
        <div class="card h-100">
            <a href="{{ image.image.url }}" title="Image for {{exercise}}">
                <img class="card-img-top" src="{{ image.image|thumbnail_url:'large' }}">
            </a>
            <div class="card-body text-center">
                {% if perms.exercises.change_exerciseimage %}
                    <a href="{% url 'exercise:image:delete' exercise.pk image.pk %}" class="wger-modal-dialog btn btn-link">
                         <span class="{% fa_class 'trash' %}"></span>
                    </a>
                    <a href="{% url 'exercise:image:edit' image.pk %}" class="btn btn-link">
                         <span class="{% fa_class 'edit' %}"></span>
                    </a>
                {% endif %}

                {% if image.is_main %}
                <p class="card-text text-wger-green">
                    <span class="{% fa_class 'medal' %}"></span></a>
                </p>
                {% endif %}
            </div>
            <div class="card-footer">
                {{image.get_license_display}}
                {% if image.license_author %}
                    {{image.license_author}}
                {% endif %}
            </div>
        </div>
        </div>
    {% endfor %}
    {% endwith %}
    </div>

    {% if perms.exercises.change_exerciseimage %}
        <p>
            <a href="{% url 'exercise:image:add' exercise.id %}" >
                {% trans "Add new image" %}
            </a>
        </p>
    {% endif %}
{% endif %}
{% endwith %}

{% if perms.exercises.change_exerciseimage %}
{% with images=exercise.images.pending %}
{% if images %}
<h5 class="mt-4">{% trans "Images pending review" %}</h5>
<div class="card-deck">
    {% for image in images %}
        <div class="card">
                <img class="card-img-top" src="{{ image.image|thumbnail_url:'small' }}">
                <div class="card-body">
                    <a href="{% url 'exercise:image:accept' image.pk %}" class="btn btn-light btn-sm">{% trans "Accept" %}</a>
                    <a href="{% url 'exercise:image:decline' image.pk %}" class="btn btn-light btn-sm">{% trans "Decline" %}</a>
                    <a href="{% url 'exercise:image:delete' exercise.pk image.pk %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                 </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endif %}  {# end check permission #}


{# Comments #}
{% with comments=exercise.exercisecomment_set.all %}
{% if comments or perms.exercises.change_exercisecomment %}
    <h5 class="mt-4">{% trans "Comments for this exercise" %}:</h5>
    <ul>
    {% for comment in comments %}
        <li>
            {{ comment }}

            {% if perms.exercises.change_exercisecomment %}
            <span class="dropdown">
                <button type="button" class="btn btn-link dropdown-toggle btn-sm" data-toggle="dropdown"></button>
                <div class="dropdown-menu">
                    <a href="{% url 'exercise:comment:edit' comment.id %}" class="dropdown-item wger-modal-dialog">
                        <span class="{% fa_class 'edit' %}"></span>
                        {% trans 'Edit' %}
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'exercise:comment:delete' comment.id %}" class="dropdown-item">
                        <span class="{% fa_class 'trash' %}"></span>
                        {% trans 'Delete' %}
                    </a>
                </div>
            </span>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% if perms.exercises.change_exercisecomment %}
        <p>
            <a href="{% url 'exercise:comment:add' exercise.id %}" class="wger-modal-dialog">
                {% trans "Add new comment" %}
            </a>
        </p>
    {% endif %}
{% endif %}
{% endwith %}




{% cache cache_timeout exercise-detail-muscles cache_vary_on %}
{% if muscles_main_front or muscles_main_back %}
    <h5 class="mt-4">{% trans "Muscles" %}:</h5>
    <p>
        {% trans "The diagram shows the most used muscles on this exercise" %}
    </p>
    <p>
        <div style="width:1em;height:1em;background-color:#cc0000;float:left;margin-right:0.5em;"></div>
        {% trans "Main muscles" %}
    </p>
    <p>
        <div style="width:1em;height:1em;background-color:#f57900;float:left;margin-right:0.5em;"></div>
        {% trans "Secondary muscles" %}
    </p>

    <div class="row ">
        <div class="col">
            {% render_muscles muscles_main_front muscles_sec_front %}
            <ul class="list-unstyled text-center">
                {% for muscle in muscles_main_front %}
                    <li>{{muscle.name}}</li>
                {% endfor %}

                {% for muscle in muscles_sec_front %}
                    <li>{{muscle.name}}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col">
            {% render_muscles muscles_main_back muscles_sec_back %}
            <ul class="list-unstyled text-center">
                {% for muscle in muscles_main_back %}
                    <li>{{muscle.name}}</li>
                {% endfor %}

                {% for muscle in muscles_sec_back %}
                    <li>{{muscle.name}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endif %}
{% endcache %}

{% if logs %}
    <h5 class="mt-4">{% trans "Weight log" %}:</h5>
    {% render_weight_log logs svg_uuid user %}
{% endif %}

{% if exercise.variations %}
    <h5 class="mt-4">{% trans "Exercise Variations" %}:</h5>
        <ul>
        {% for variation in exercise.variations %}
            <li>
                <a href="{{ variation.get_absolute_url }}">{{ variation }}</a>
            </li>
        {% endfor %}
        </ul>
{% endif %}
{% endblock %}


{#          #}
{# Side bar #}
{#          #}
{% block sidebar %}
{% if user.is_authenticated and not user.userprofile.is_temporary and not perms.exercises %}
<h5>{% trans "Options" %}</h5>
<p>
    <a href="{% url 'exercise:exercise:correct' exercise.id %}">
        <span class="{% fa_class 'edit' %}"></span>
        {% trans "Submit a correction" %}
    </a>
</p>
{% endif %}

{% license_sidebar exercise.license exercise.license_author %}
{% endblock %}



{#         #}
{# Options #}
{#         #}
{% block options %}
{% if perms.exercises.change_exercise %}
<div class="btn-group">
    <div class="btn-group">
        <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="{% fa_class 'cog' %}"></span>
            {% trans "Options" %}
        </button>
        <div class="dropdown-menu">
            <a href="{% url 'exercise:exercise:edit' exercise.id %}" class="dropdown-item">
                <span class="{% fa_class 'edit' %}"></span>
                {% trans "Edit" %}
            </a>
            <div role="separator" class="dropdown-divider"></div>
            <a href="{% url 'exercise:exercise:delete' exercise.id %}" class="wger-modal-dialog dropdown-item">
                <span class="{% fa_class 'trash' %}"></span>
                {% trans "Delete" %}
            </a>
            </li>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}